repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-format
        files: \.(py|ipynb)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|scss|html|json|md|markdown|yaml|yml)$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        files: ^baÏ€ckend/src/.*\.py$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
        args: ["--fix"]
        files: \.(md|markdown|mdown|myst)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.28.0
    hooks:
      - id: eslint
        args: ["--fix"]
        files: \.[jt]sx?$
