[package]
name = "scoring-native"
version = "0.1.0"
edition = "2021"

[lib]
name = "scoring_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["extension-module"] }
array2d = "0.3.2"

[build-dependencies]
pyo3-build-config = "0.26"
