[package]
name = "scoring-native"
version = "0.1.0"
edition = "2021"

[lib]
name = "scoring_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["extension-module"] }
ndarray = "0.16"
ndarray-stats = "0.6"
ndarray-conv = "0.5"

[build-dependencies]
pyo3-build-config = "0.26"
