# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notes.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, "", "notes.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bnotes.proto"x\n\x04Note\x12\r\n\x05pitch\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\x02\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\x12\x10\n\x08velocity\x18\x04 \x01(\x02\x12\x0c\n\x04page\x18\x05 \x01(\x05\x12\r\n\x05track\x18\x06 \x01(\x05\x12\x0c\n\x04\x62\x62ox\x18\x07 \x03(\x05".\n\x08NoteList\x12\x14\n\x05notes\x18\x01 \x03(\x0b\x32\x05.Note\x12\x0c\n\x04size\x18\x02 \x03(\x05"s\n\x04\x45\x64it\x12!\n\toperation\x18\x01 \x01(\x0e\x32\x0e.EditOperation\x12\x0b\n\x03pos\x18\x02 \x01(\x05\x12\x15\n\x06s_char\x18\x03 \x01(\x0b\x32\x05.Note\x12\x15\n\x06t_char\x18\x04 \x01(\x0b\x32\x05.Note\x12\r\n\x05t_pos\x18\x05 \x01(\x05".\n\x08\x45\x64itList\x12\x14\n\x05\x65\x64its\x18\x01 \x03(\x0b\x32\x05.Edit\x12\x0c\n\x04size\x18\x02 \x03(\x05*7\n\rEditOperation\x12\n\n\x06INSERT\x10\x00\x12\x0e\n\nSUBSTITUTE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "notes_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EDITOPERATION"]._serialized_start = 350
    _globals["_EDITOPERATION"]._serialized_end = 405
    _globals["_NOTE"]._serialized_start = 15
    _globals["_NOTE"]._serialized_end = 135
    _globals["_NOTELIST"]._serialized_start = 137
    _globals["_NOTELIST"]._serialized_end = 183
    _globals["_EDIT"]._serialized_start = 185
    _globals["_EDIT"]._serialized_end = 300
    _globals["_EDITLIST"]._serialized_start = 302
    _globals["_EDITLIST"]._serialized_end = 348
# @@protoc_insertion_point(module_scope)
