name: build-and-publish

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: PyO3/maturin-action@v1
        with:
          manylinux: "2014"
          command: build
          args: --release
          working-directory: backend/scoring

      - uses: PyO3/maturin-action@v1
        with:
          command: sdist
          working-directory: backend/scoring

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            backend/scoring/target/wheels/*.whl
            backend/scoring/target/wheels/*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: scoring-crate-builder
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
