name: build-and-publish

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare dist dir
        run: mkdir -p dist && chmod -R a+rwx dist

      - name: Build wheels (manylinux2014)
        uses: PyO3/maturin-action@v1
        with:
          manylinux: "2014"
          command: build
          args: --release --out ../../dist
          working-directory: backend/scoring

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out ../../dist
          working-directory: backend/scoring

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/*.whl
            dist/*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: scoring-crate-builder
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
