name: build-and-publish

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --manylinux 2014 -i python3.8 -i python3.9 -i python3.10 -i python3.11 -i python3.12
      - name: Build sdist
        run: python -m pip install maturin && maturin sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            target/wheels/*.whl
            target/wheels/*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: scoring-crate-builder
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
